
--SELECT STATEMENT--
SELECT * FROM CUSTOMERS

SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,PHONE,EMAIL,CITY,STATE FROM CUSTOMERS

SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,(FIRST_NAME + ' '+LAST_NAME)AS NAME,EMAIL,CITY FROM CUSTOMERS


